const Image = {
    1:require('./characters/Ace.png'),
    2:require('./characters/Adagio Dazzle.png'),
    3:require('./characters/Ahuizotl.png'),
    4:require('./characters/All Aboard.png'),
    5:require('./characters/Amber Waves.png'),
    6:require('./characters/Amethyst Maresbury.png'),
    7:require('./characters/Amethyst Star (human).png'),
    8:require('./characters/Amethyst Star.png'),
    9:require('./characters/Amira.png'),
    10:require('./characters/Angel Wings.png'),
    11:require('./characters/Angel.png'),
    12:require('./characters/Apple Bloom.png'),
    13:require('./characters/Apple Brown Betty.png'),
    14:require('./characters/Apple Bumpkin.png'),
    15:require('./characters/Apple Cider.png'),
    16:require('./characters/Apple Cinnamon.png'),
    17:require('./characters/Apple Cobbler.png'),
    18:require('./characters/Apple Dumpling.png'),
    19:require('./characters/Apple Flora.png'),
    20:require('./characters/Apple Fritter.png'),
    21:require('./characters/Apple Honey.png'),
    22:require('./characters/Apple Leaves.png'),
    23:require('./characters/Apple Munchies.png'),
    24:require('./characters/Apple Pie.png'),
    25:require('./characters/Apple Rose.png'),
    26:require('./characters/Apple Split.png'),
    27:require('./characters/Apple Stars.png'),
    28:require('./characters/Apple Strudel.png'),
    29:require('./characters/Applebloom (human).png'),
    30:require('./characters/Applejack (human).png'),
    31:require('./characters/Applejack.png'),
    32:require('./characters/Appleloosa deputies.png'),
    33:require('./characters/Applesauce.png'),
    34:require('./characters/Aria Blaze.png'),
    35:require('./characters/Aunt Holiday.png'),
    36:require('./characters/Aunt Orange.png'),
    37:require('./characters/Auntie Lofty.png'),
    38:require('./characters/Aura.png'),
    39:require('./characters/Autumn Blaze Nirik.png'),
    40:require('./characters/Autumn Blaze.png'),
    41:require('./characters/Babs Seed.png'),
    42:require('./characters/Banana Fluff.png'),
    43:require('./characters/Barber Groomsby.png'),
    44:require('./characters/Beauty Brass.png'),
    45:require('./characters/Berry Dreams.png'),
    46:require('./characters/Berryshine.png'),
    47:require('./characters/Big McIntosh (human).png'),
    48:require('./characters/Big McIntosh.png'),
    49:require('./characters/Bill Neigh.png'),
    50:require('./characters/Bittersweet.png'),
    51:require('./characters/Blaze.png'),
    52:require('./characters/Blossomforth.png'),
    53:require('./characters/Blue Moon.png'),
    54:require('./characters/Bow Hothoof.png'),
    55:require('./characters/Braeburn.png'),
    56:require('./characters/Bright Mac.png'),
    57:require('./characters/Bright Smile.png'),
    58:require('./characters/Bubblegum Blossom.png'),
    59:require('./characters/Buddy.png'),
    60:require('./characters/Bufogren.png'),
    61:require('./characters/Bugbear.png'),
    62:require('./characters/Bulk Biceps (human).png'),
    63:require('./characters/Bulk Biceps.png'),
    64:require('./characters/Bushel.png'),
    65:require('./characters/Button Mash.png'),
    66:require('./characters/Candy Apples.png'),
    67:require('./characters/Candy Mane.png'),
    68:require('./characters/Canter Zoom.png'),
    69:require('./characters/Capper.png'),
    70:require('./characters/Captain Celaeno.png'),
    71:require('./characters/Caramel Apple.png'),
    72:require('./characters/Caramel.png'),
    73:require('./characters/Cayenne.png'),
    74:require('./characters/Celestia.png'),
    75:require('./characters/Cerberus.png'),
    76:require('./characters/Chancellor Neighsay.png'),
    77:require('./characters/Charged Up.png'),
    78:require('./characters/Charm.png'),
    79:require('./characters/Cheerilee (human).png'),
    80:require('./characters/Cheerilee.png'),
    81:require('./characters/Cheese Sandwich.png'),
    82:require('./characters/Chelsea Porcelain.png'),
    83:require('./characters/Cherry Berry.png'),
    84:require('./characters/Cherry Fizzy.png'),
    85:require('./characters/Cherry Gold.png'),
    86:require('./characters/Cherry Jubilee.png'),
    87:require('./characters/Cherry Spices.png'),
    88:require('./characters/Chestnut Magnifico.png'),
    89:require('./characters/Chief Thunderhooves.png'),
    90:require('./characters/Chimera.png'),
    91:require('./characters/Cipactli.png'),
    92:require('./characters/Citrus Blush.png'),
    93:require('./characters/Claude.png'),
    94:require('./characters/Clear Sky.png'),
    95:require('./characters/Cloud Chaser.png'),
    96:require('./characters/Cloud Kicker.png'),
    97:require('./characters/Cloudy Quartz.png'),
    98:require('./characters/Cockatrice.png'),
    99:require('./characters/Coco Crusoe.png'),
    100:require('./characters/Coco Pommel.png'),
    101:require('./characters/Coloratura (human).png'),
    102:require('./characters/Coloratura.png'),
    103:require('./characters/Comet Tail.png'),
    104:require('./characters/Compass Star.png'),
    105:require('./characters/Constance.png'),
    106:require('./characters/Coriander Cumin.png'),
    107:require('./characters/Cotton Cloudy.png'),
    108:require('./characters/Count Caesar.png'),
    109:require('./characters/Cozy Glow.png'),
    110:require('./characters/Crafty Crate.png'),
    111:require('./characters/Cragadile.png'),
    112:require('./characters/Cranky Doodle (human).png'),
    113:require('./characters/Cranky Doodle Donkey.png'),
    114:require('./characters/Crescent Moon.png'),
    115:require('./characters/Crystal Arrow.png'),
    116:require('./characters/Dainty Dove.png'),
    117:require('./characters/Daisy.png'),
    118:require('./characters/Dance Fever.png'),
    119:require('./characters/Daring Do.png'),
    120:require('./characters/Dark Moon.png'),
    121:require('./characters/Davenport.png'),
    122:require('./characters/DD Fido.png'),
    123:require('./characters/DD Rover.png'),
    124:require('./characters/DD Spot.png'),
    125:require('./characters/Derpy (human).png'),
    126:require('./characters/Derpy.png'),
    127:require('./characters/Diamond Mint.png'),
    128:require('./characters/Diamond Tiara (human).png'),
    129:require('./characters/Diamond Tiara.png'),
    130:require('./characters/Dinky Doo.png'),
    131:require('./characters/Discord.png'),
    132:require('./characters/DJ Pon-3.png'),
    133:require('./characters/Doc Top.png'),
    134:require('./characters/Doctor Horse.png'),
    135:require('./characters/Donny Kerabatsos.png'),
    136:require('./characters/Double Diamond.png'),
    137:require('./characters/Dr. Caballeron.png'),
    138:require('./characters/Dr. Hooves.png'),
    139:require('./characters/Drizzle.png'),
    140:require('./characters/Dumbbell.png'),
    141:require('./characters/Eclair Creme.png'),
    142:require('./characters/Eiffel.png'),
    143:require('./characters/Elbow Grease.png'),
    144:require('./characters/Electric Sky.png'),
    145:require('./characters/Emerald Green.png'),
    146:require('./characters/Fancy Pants.png'),
    147:require('./characters/Fast clip.png'),
    148:require('./characters/Feather Bangs.png'),
    149:require('./characters/Featherweight.png'),
    150:require('./characters/Felix.png'),
    151:require('./characters/Fetter Keys.png'),
    152:require('./characters/Fiddly Twang.png'),
    153:require('./characters/Filthy Rich.png'),
    154:require('./characters/Fine Line.png'),
    155:require('./characters/Fire Streak.png'),
    156:require('./characters/Firelight.png'),
    157:require('./characters/Flam (human).png'),
    158:require('./characters/Flam.png'),
    159:require('./characters/Flash Magnus.png'),
    160:require('./characters/Flash Sentry (human).png'),
    161:require('./characters/Flash Sentry.png'),
    162:require('./characters/Fleetfoot.png'),
    163:require('./characters/Fleur de Verre.png'),
    164:require('./characters/Fleur Dis Lee (human).png'),
    165:require('./characters/Fleur Dis Lee.png'),
    166:require('./characters/Flim (human).png'),
    167:require('./characters/Flim.png'),
    168:require('./characters/Flitter.png'),
    169:require('./characters/Florina Tart.png'),
    170:require('./characters/Flurry Heart.png'),
    171:require('./characters/Fluttershy (human).png'),
    172:require('./characters/Fluttershy.png'),
    173:require('./characters/Foggy Fleece.png'),
    174:require('./characters/Four Step.png'),
    175:require('./characters/Fruit bats.png'),
    176:require('./characters/Future Spike.png'),
    177:require('./characters/Future Twilight Sparkle.png'),
    178:require('./characters/Gabby.png'),
    179:require('./characters/Gala Appleby.png'),
    180:require('./characters/Gallus.png'),
    181:require('./characters/Garble.png'),
    182:require('./characters/Geri.png'),
    183:require('./characters/Gilda.png'),
    184:require('./characters/Giselle.png'),
    185:require('./characters/Gizmo.png'),
    186:require('./characters/Gladmane.png'),
    187:require('./characters/Globe Trotter.png'),
    188:require('./characters/Gloriosa Daisy.png'),
    189:require('./characters/Golden Delicious.png'),
    190:require('./characters/Golden Harvest.png'),
    191:require('./characters/Goldengrape.png'),
    192:require('./characters/Goldie Delicious.png'),
    193:require('./characters/Grampa Gruff.png'),
    194:require('./characters/Grand Pear.png'),
    195:require('./characters/Granny Smith (human).png'),
    196:require('./characters/Granny Smith.png'),
    197:require('./characters/Green Jewel.png'),
    198:require('./characters/Greta.png'),
    199:require('./characters/Grogar.png'),
    200:require('./characters/Grubber.png'),
    201:require('./characters/Gummy.png'),
    202:require('./characters/Gustave.png'),
    203:require('./characters/Haakim.png'),
    204:require('./characters/Half Baked Apple.png'),
    205:require('./characters/Harry.png'),
    206:require('./characters/Hayseed Turnip.png'),
    207:require('./characters/Helia.png'),
    208:require('./characters/High Winds.png'),
    209:require('./characters/Hitch Trailblazer.png'),
    210:require('./characters/Hoity Toity.png'),
    211:require('./characters/Holly Dash.png'),
    212:require('./characters/Hondo Flanks.png'),
    213:require('./characters/Honey Rays.png'),
    214:require('./characters/Hoops.png'),
    215:require('./characters/Hughbert Jellius.png'),
    216:require('./characters/Hydra.png'),
    217:require('./characters/Igneous Rock.png'),
    218:require('./characters/Indigo Zap.png'),
    219:require('./characters/Inky Rose.png'),
    220:require('./characters/Iron Will.png'),
    221:require('./characters/Ivory.png'),
    222:require('./characters/Izzy Moonbow.png'),
    223:require('./characters/Jack Hammer.png'),
    224:require('./characters/Jack Pot.png'),
    225:require('./characters/Jeff Letrotski.png'),
    226:require('./characters/Jet Set (human).png'),
    227:require('./characters/Jet Set.png'),
    228:require('./characters/Jetstream.png'),
    229:require('./characters/Joe.png'),
    230:require('./characters/Jonagold.png'),
    231:require('./characters/Junebug.png'),
    232:require('./characters/Juniper Montage (human).png'),
    233:require('./characters/Juniper Montage.png'),
    234:require('./characters/King Sombra.png'),
    235:require('./characters/Kiwi Lollipop.png'),
    236:require('./characters/Lady Justice.png'),
    237:require('./characters/Lavender Bloom.png'),
    238:require('./characters/Lavender Fritter.png'),
    239:require('./characters/Leadwing.png'),
    240:require('./characters/Lemon Hearts.png'),
    241:require('./characters/Lemon Zest.png'),
    242:require('./characters/Lemony Gem.png'),
    243:require('./characters/Lightning Dust.png'),
    244:require('./characters/Lilac Links.png'),
    245:require('./characters/Lilac Sky.png'),
    246:require('./characters/Lily Lace.png'),
    247:require('./characters/Lily Valley.png'),
    248:require('./characters/Limestone Pie.png'),
    249:require('./characters/Little Strongheart.png'),
    250:require('./characters/Liza Doolots.png'),
    251:require('./characters/Lotus Blossom.png'),
    252:require('./characters/Luckette.png'),
    253:require('./characters/Lucky Clover.png'),
    254:require('./characters/Lucky Star.png'),
    255:require('./characters/Luster Dawn.png'),
    256:require('./characters/Lyra Heartstrings (human).png'),
    257:require('./characters/Lyra Heartstrings.png'),
    258:require('./characters/Lyrica Lilac.png'),
    259:require('./characters/Mage Meadowbrook.png'),
    260:require('./characters/Magnet Bolt.png'),
    261:require('./characters/Mane Allgood.png'),
    262:require('./characters/Mane Goodall.png'),
    263:require('./characters/Mane-iac.png'),
    264:require('./characters/Mango Dash.png'),
    265:require('./characters/Manny.png'),
    266:require('./characters/Marble Pie.png'),
    267:require('./characters/Matilda.png'),
    268:require('./characters/Maud Pie (human).png'),
    269:require('./characters/Maud Pie.png'),
    270:require('./characters/Maulwurf.png'),
    271:require('./characters/Mayor Mare.png'),
    272:require('./characters/Meadow Flower.png'),
    273:require('./characters/Meadow Song.png'),
    274:require('./characters/Merry May.png'),
    275:require('./characters/Metamorphosed Pharynx.png'),
    276:require('./characters/Micro Chips.png'),
    277:require('./characters/Minty.png'),
    278:require('./characters/Minuette.png'),
    279:require('./characters/Mistmane.png'),
    280:require('./characters/Misty Fly.png'),
    281:require('./characters/Mjolna.png'),
    282:require('./characters/Moon Dancer.png'),
    283:require('./characters/Moonlight Raven.png'),
    284:require('./characters/Mr. Breezy.png'),
    285:require('./characters/Mr. Cake.png'),
    286:require('./characters/Mr. Greenhooves.png'),
    287:require('./characters/Mr. Shy.png'),
    288:require('./characters/Mr. Stripes.png'),
    289:require('./characters/Mr. Waddle.png'),
    290:require('./characters/Mrs. Cake.png'),
    291:require('./characters/Mrs. Shy.png'),
    292:require('./characters/Ms. Harshwhinny.png'),
    293:require('./characters/Ms. Peachbottom.png'),
    294:require('./characters/Mudbriar.png'),
    295:require('./characters/Mulia Mild.png'),
    296:require('./characters/Neon Lights (human).png'),
    297:require('./characters/Neon Lights.png'),
    298:require('./characters/Night Glider.png'),
    299:require('./characters/Night Knight.png'),
    300:require('./characters/Night Light.png'),
    301:require('./characters/Nightmare Moon.png'),
    302:require('./characters/Noi.png'),
    303:require('./characters/North Point.png'),
    304:require('./characters/Noteworthy.png'),
    305:require('./characters/Nurse Redheart.png'),
    306:require('./characters/Ocean Flow.png'),
    307:require('./characters/Ocellus.png'),
    308:require('./characters/Octavia Melody (human).png'),
    309:require('./characters/Octavia Melody.png'),
    310:require('./characters/Opalescence.png'),
    311:require('./characters/Orange Swirl.png'),
    312:require('./characters/Orthros.png'),
    313:require('./characters/Owlowiscious.png'),
    314:require('./characters/Paleo family.png'),
    315:require('./characters/Parasol.png'),
    316:require('./characters/Parasprite.png'),
    317:require('./characters/Parcel Post.png'),
    318:require('./characters/Parish Nandermane.png'),
    319:require('./characters/Party Favor.png'),
    320:require('./characters/Peachy Pitt.png'),
    321:require('./characters/Peachy Sweet.png'),
    322:require('./characters/Pear Butter.png'),
    323:require('./characters/Pearly Stitch.png'),
    324:require('./characters/Peewee.png'),
    325:require('./characters/Perfect Pace.png'),
    326:require('./characters/Pharynx.png'),
    327:require('./characters/Philomena.png'),
    328:require('./characters/Photo Finish (human).png'),
    329:require('./characters/Photo Finish.png'),
    330:require('./characters/Pina Colada.png'),
    331:require('./characters/Pinkie Pie (human).png'),
    332:require('./characters/Pinkie Pie.png'),
    333:require('./characters/Pinny Lane.png'),
    334:require('./characters/Pipp Petals.png'),
    335:require('./characters/Pipsqueak.png'),
    336:require('./characters/Pixel Pizzaz.png'),
    337:require('./characters/Pizzelle.png'),
    338:require('./characters/Ponet.png'),
    339:require('./characters/Pony of Shadows.png'),
    340:require('./characters/Pound Cake.png'),
    341:require('./characters/Prim Hemline (human).png'),
    342:require('./characters/Prim Hemline.png'),
    343:require('./characters/Prim Posy.png'),
    344:require('./characters/Prince Rutherford.png'),
    345:require('./characters/Princess Amore.png'),
    346:require('./characters/Princess Cadance.png'),
    347:require('./characters/Princess Ember.png'),
    348:require('./characters/Princess Erroria.png'),
    349:require('./characters/Princess Luna.png'),
    350:require('./characters/Princess Skystar.png'),
    351:require('./characters/Principal Celestia (human).png'),
    352:require('./characters/Principal Cinch.png'),
    353:require('./characters/Pumpkin Cake.png'),
    354:require('./characters/Purple Wave.png'),
    355:require('./characters/Pursey Pink.png'),
    356:require('./characters/Quarray eels.png'),
    357:require('./characters/Queen Chrysalis.png'),
    358:require('./characters/Queen Novo.png'),
    359:require('./characters/Quibble Pants.png'),
    360:require('./characters/Rainbow Blaze.png'),
    361:require('./characters/Rainbow Dash (human).png'),
    362:require('./characters/Rainbow Dash.png'),
    363:require('./characters/Rainbow Stars.png'),
    364:require('./characters/Rainbow Swoop.png'),
    365:require('./characters/Rainbowshine.png'),
    366:require('./characters/Rainy Feather.png'),
    367:require('./characters/Randolph (human).png'),
    368:require('./characters/Randolph.png'),
    369:require('./characters/Rare Find.png'),
    370:require('./characters/Rarity (human).png'),
    371:require('./characters/Rarity.png'),
    372:require('./characters/Raven.png'),
    373:require('./characters/Ray.png'),
    374:require('./characters/Red Delicious.png'),
    375:require('./characters/Red Gala.png'),
    376:require('./characters/Richard Hoovenheart.png'),
    377:require('./characters/Ripley.png'),
    378:require('./characters/Rivet.png'),
    379:require('./characters/Roc.png'),
    380:require('./characters/Rockhoof.png'),
    381:require('./characters/Roma.png'),
    382:require('./characters/Rose.png'),
    383:require('./characters/Royal Pin.png'),
    384:require('./characters/Royal Ribbon.png'),
    385:require('./characters/Royal Riff.png'),
    386:require('./characters/Rubinstein.png'),
    387:require('./characters/Ruby Pinch.png'),
    388:require('./characters/Ruby Splash.png'),
    389:require('./characters/Rumble.png'),
    390:require('./characters/Sandalwood.png'),
    391:require('./characters/Sandbar.png'),
    392:require('./characters/Sapphire Joy.png'),
    393:require('./characters/Sapphire Shores.png'),
    394:require('./characters/Sassaflash.png'),
    395:require('./characters/Sassy Saddles.png'),
    396:require('./characters/Savoir Fare.png'),
    397:require('./characters/Sci-Twi.png'),
    398:require('./characters/Scootaloo (human).png'),
    399:require('./characters/Scootaloo.png'),
    400:require('./characters/Score.png'),
    401:require('./characters/Scorpan.png'),
    402:require('./characters/Screwball.png'),
    403:require('./characters/Screwy.png'),
    404:require('./characters/Sea Swirl.png'),
    405:require('./characters/Seabreeze.png'),
    406:require('./characters/Sealed Scroll.png'),
    407:require('./characters/Serena.png'),
    408:require('./characters/Serenity.png'),
    409:require('./characters/Shady Daze.png'),
    410:require('./characters/Sheriff Silverstar.png'),
    411:require('./characters/Shining Armor.png'),
    412:require('./characters/Shoeshine.png'),
    413:require('./characters/Shooting Star.png'),
    414:require('./characters/Silver Berry.png'),
    415:require('./characters/Silver Script.png'),
    416:require('./characters/Silver Shill.png'),
    417:require('./characters/Silver Spanner.png'),
    418:require('./characters/Silver Spoon (human).png'),
    419:require('./characters/Silver Spoon.png'),
    420:require('./characters/Silver Zoom.png'),
    421:require('./characters/Silverspeed.png'),
    422:require('./characters/Silverstream.png'),
    423:require('./characters/Sir Pony Moore.png'),
    424:require('./characters/Sky Beak.png'),
    425:require('./characters/Sky Stinger.png'),
    426:require('./characters/Sludge.png'),
    427:require('./characters/Smoky\'s Family.png'),
    428:require('./characters/Smolde.png'),
    429:require('./characters/Smooze.png'),
    430:require('./characters/Snail (human).png'),
    431:require('./characters/Snails.png'),
    432:require('./characters/Snap Shutter.png'),
    433:require('./characters/Snips (human).png'),
    434:require('./characters/Snips.png'),
    435:require('./characters/Soarin.png'),
    436:require('./characters/Somnambula.png'),
    437:require('./characters/Sonata Dusk.png'),
    438:require('./characters/Songbird Serenade.png'),
    439:require('./characters/Sour Sweet.png'),
    440:require('./characters/Spearhead.png'),
    441:require('./characters/Sphinx.png'),
    442:require('./characters/Spike (dog).png'),
    443:require('./characters/Spike.png'),
    444:require('./characters/Spitfire.png'),
    445:require('./characters/Spoiled Rich.png'),
    446:require('./characters/Spring Forward.png'),
    447:require('./characters/Spring Step.png'),
    448:require('./characters/Sprinkle Medley.png'),
    449:require('./characters/Star Bright.png'),
    450:require('./characters/Star Gazer.png'),
    451:require('./characters/Star Hunter.png'),
    452:require('./characters/Star Spur.png'),
    453:require('./characters/Star Swirl.png'),
    454:require('./characters/Starburst.png'),
    455:require('./characters/Starlight Glimmer (human).png'),
    456:require('./characters/Starlight Glimmer.png'),
    457:require('./characters/Starry Eyes.png'),
    458:require('./characters/Starstreak.png'),
    459:require('./characters/Stellar Eclipse.png'),
    460:require('./characters/Stellar Flare.png'),
    461:require('./characters/Steven Magnet.png'),
    462:require('./characters/Storm creatures.png'),
    463:require('./characters/Stormfeather.png'),
    464:require('./characters/Strawberry bats.png'),
    465:require('./characters/Strawberry Ice.png'),
    466:require('./characters/Strawberry Sunrise.png'),
    467:require('./characters/Strike.png'),
    468:require('./characters/Stygian.png'),
    469:require('./characters/Sugar Belle.png'),
    470:require('./characters/Sugarcoat.png'),
    471:require('./characters/Sunburst.png'),
    472:require('./characters/Sunny Daze.png'),
    473:require('./characters/Sunny Flare.png'),
    474:require('./characters/Sunny Rays.png'),
    475:require('./characters/Sunny Starscout.png'),
    476:require('./characters/Sunset Shimmer (human).png'),
    477:require('./characters/Sunset Shimmer.png'),
    478:require('./characters/Sunshine Petals.png'),
    479:require('./characters/Sunshine Smiles.png'),
    480:require('./characters/Sunshower Raindrops.png'),
    481:require('./characters/Supernova Zap.png'),
    482:require('./characters/Suri Polomare (human).png'),
    483:require('./characters/Suri Polomare.png'),
    484:require('./characters/Surprise.png'),
    485:require('./characters/Svengallop.png'),
    486:require('./characters/Sweet Pop.png'),
    487:require('./characters/Sweet Tooth.png'),
    488:require('./characters/Sweetie Belle (human).png'),
    489:require('./characters/Sweetie Belle.png'),
    490:require('./characters/Sweetie Drops (human).png'),
    491:require('./characters/Sweetie Drops.png'),
    492:require('./characters/Tall Order.png'),
    493:require('./characters/Tank.png'),
    494:require('./characters/Tatzlwurm.png'),
    495:require('./characters/Teddie Safari.png'),
    496:require('./characters/Tempest Shadow.png'),
    497:require('./characters/Tender Taps.png'),
    498:require('./characters/Terramar Hippogriff.png'),
    499:require('./characters/Terramar seapony.png'),
    500:require('./characters/The Shadowbolts.png'),
    501:require('./characters/The Storm King.png'),
    502:require('./characters/The timberwolves.png'),
    503:require('./characters/Thorax (New Form).png'),
    504:require('./characters/Thorn.png'),
    505:require('./characters/Thunderlane.png'),
    506:require('./characters/Timber Spruce.png'),
    507:require('./characters/Tirek.png'),
    508:require('./characters/Toola Roola.png'),
    509:require('./characters/Top Marks.png'),
    510:require('./characters/Tornado Bolt.png'),
    511:require('./characters/Tree Hugger.png'),
    512:require('./characters/Trenderhoof (human).png'),
    513:require('./characters/Trenderhoof.png'),
    514:require('./characters/Trixie (human).png'),
    515:require('./characters/Trixie.png'),
    516:require('./characters/Trouble Shoes.png'),
    517:require('./characters/Truffle Shuffle.png'),
    518:require('./characters/Twilight Sky.png'),
    519:require('./characters/Twilight Sparkle (human).png'),
    520:require('./characters/Twilight Velvet.png'),
    521:require('./characters/Twilight.png'),
    522:require('./characters/Twinkleshine.png'),
    523:require('./characters/Twist smiles.png'),
    524:require('./characters/Uncle Orange.png'),
    525:require('./characters/unnamed pony 1.png'),
    526:require('./characters/Ursa major.png'),
    527:require('./characters/Ursa minor.png'),
    528:require('./characters/Vapor Trail.png'),
    529:require('./characters/Vice Principal Luna (human).png'),
    530:require('./characters/Vidala Swoon.png'),
    531:require('./characters/Vignette Valencia.png'),
    532:require('./characters/Violet Blurr.png'),
    533:require('./characters/Wallflower Blush.png'),
    534:require('./characters/Walter.png'),
    535:require('./characters/Warm Front.png'),
    536:require('./characters/Wensley.png'),
    537:require('./characters/Whiplash.png'),
    538:require('./characters/White Lightning.png'),
    539:require('./characters/Whitewash.png'),
    540:require('./characters/Whoa Nelly.png'),
    541:require('./characters/Wild Fire.png'),
    542:require('./characters/Wind Rider.png'),
    543:require('./characters/Wind Sprint.png'),
    544:require('./characters/Windigoes.png'),
    545:require('./characters/Winona.png'),
    546:require('./characters/Winterchilla.png'),
    547:require('./characters/Winterzilla.png'),
    548:require('./characters/Wisp.png'),
    549:require('./characters/Written Script.png'),
    550:require('./characters/Yona.png'),
    551:require('./characters/Zecora.png'),
    552:require('./characters/Zephyr Breeze (human).png'),
    553:require('./characters/Zephyr Breeze.png'),
    554:require('./characters/Zesty Gourmand.png'),
    555:require('./characters/Zipp Storm.png'),
    556:require('./characters/Zipporwhill.png'),
       
}

export default Image